please-scan-member:
  pods:
    replicas: 1

    resources:
      limits:
        cpu: 300m
        memory: 350Mi
      requests:
        cpu: 150m
        memory: 100Mi

    env:
      - name: ENV_GROUP
        value: 'dev'

      - name: ENV_RUN
        value: 'Development'

      - name: NODE_ENV
        value: 'Development'

      - name: NEXT_PUBLIC_API_URL
        value: 'http://please-scan-dev-onix-api'

      - name: NEXT_PUBLIC_PROVIDER_URL
        value: 'https://web-dev.dev-hubs.com'
