---
envAlias: development
envAliasJob: Development
envGroup: dev

domainOnixScanAPI: api-dev.please-scan.local
pleaseScanAdminDomain: admin-dev.please-scan.local
pleaseScanTenantDomain: tenant-dev.please-scan.local
pleaseScanWebDomain: web-dev.please-scan.local
pleaseScanRegisterDomain: register-dev.please-scan.local
pleaseScanVerifyDomain: verify-dev.please-scan.local

pgDiskSize: 30Gi
pgHost: postgresql-onix-v2
