---
envAlias: production
envAliasJob: Production

envGroup: prod

domainOnixScanAPI: api-prod.please-scan.local
pleaseScanAdminDomain: admin-prod.please-scan.local
pleaseScanTenantDomain: tenant-prod.please-scan.local
pleaseScanWebDomain: web-prod.please-scan.local

pgDiskSize: 100Gi
pgHost: postgresql-onix-v2
