please-scan-register:
  pods:
    replicas: 1

    resources:
      limits:
        cpu: 300m
        memory: 350Mi
      requests:
        cpu: 150m
        memory: 100Mi

    env:
      - name: ENV_GROUP
        value: 'dev'

      - name: NODE_ENV
        value: "development"

      - name: RUNTIME_ENV
        value: "development"

      - name: NEXT_PUBLIC_API_URL
        value: 'http://please-scan-dev-onix-api'

      - name: LOG_ENDPOINT
        value: "http://logstash-http.logstash-soc.svc.cluster.local:8080"

      - name: NEXT_PUBLIC_LOG_ENDPOINT
        value: "http://logstash-http.logstash-soc.svc.cluster.local:8080"
