please-scan-register:
  pods:
    replicas: 1

    resources:
      limits:
        cpu: 300m
        memory: 350Mi
      requests:
        cpu: 150m
        memory: 100Mi

    env:
      - name: ENV_GROUP
        value: 'prod'

      - name: NODE_ENV
        value: "production"

      - name: RUNTIME_ENV
        value: "production"

      - name: NEXT_PUBLIC_API_URL
        value: 'http://please-scan-prod-onix-api'

      - name: REDIS_HOST
        value: "redis-master"

      - name: REDIS_PORT
        value: "6379"