apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: minio-secret
spec:
  refreshInterval: 1m
  secretStoreRef:
    kind: ClusterSecretStore
    name: k8s-secret-store      # name of the SecretStore (or kind specified)
  target:
    name: minio-secret       # name of the k8s Secret to be created
    creationPolicy: Owner
  data:
  - secretKey: MINIO_SECRET_KEY
    remoteRef:
      key: "initial-secret"
      property: GRAFANA_PASSWORD #ขอยืม grafana มาใช้

  - secretKey: MINIO_ACCESS_KEY
    remoteRef:
      key: "initial-secret"
      property: GRAFANA_USER #ขอยืม grafana มาใช้
