apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: scan-item-secret
spec:
  refreshInterval: 1m
  secretStoreRef:
    kind: ClusterSecretStore
    name: k8s-secret-store      # name of the SecretStore (or kind specified)
  target:
    name: scan-item-secret      # name of the k8s Secret to be created
    creationPolicy: Owner
  data:
  - secretKey: ENCRYPTION_KEY
    remoteRef:
      key: "initial-secret-preset"
      property: ENCRYPTION_KEY

  - secretKey: ENCRYPTION_IV
    remoteRef:
      key: "initial-secret-preset"
      property: ENCRYPTION_IV
