apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: scan-item-secret
spec:
  refreshInterval: 1m
  secretStoreRef:
    kind: ClusterSecretStore
    name: gcp-secret-store      # name of the SecretStore (or kind specified)
  target:
    name: scan-item-secret      # name of the k8s Secret to be created
    creationPolicy: Owner
  data:
  - secretKey: ENCRYPTION_KEY
    remoteRef:
      key: "{{ .Values.envAlias }}-scan-item"
      property: ENCRYPTION_KEY
      version: latest

  - secretKey: ENCRYPTION_IV
    remoteRef:
      key: "{{ .Values.envAlias }}-scan-item"
      property: ENCRYPTION_IV
      version: latest
