apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: smtp-secret
spec:
  refreshInterval: 1m
  secretStoreRef:
    kind: ClusterSecretStore
    name: k8s-secret-store      # name of the SecretStore (or kind specified)
  target:
    name: smtp-secret      # name of the k8s Secret to be created
    creationPolicy: Owner
  data:
  - secretKey: SMTP_USER
    remoteRef:
      key: "initial-secret-preset"
      property: SMTP_USER

  - secretKey: SMTP_PASSWORD
    remoteRef:
      key: "initial-secret-preset"
      property: SMTP_PASSWORD
