
please-scan-verify:
  enabled: true
  nameOverride: verify

  ingress:
    enabled: false

  podDisruptionBudget:
    enabled: false

  pods:
    controller: deployment

    readinessProbe:
      httpGet:
        path: /health
        port: 5000
      initialDelaySeconds: 20
      periodSeconds: 10
      timeoutSeconds: 5
      failureThreshold: 2

    livenessProbe:
      httpGet:
        path: /health
        port: 5000
      initialDelaySeconds: 20
      periodSeconds: 10

    image:
      name: asia-southeast1-docker.pkg.dev/its-artifact-commons/please-scan/please-scan-verify

  service:
    enabled: true
    ports:
      - port: 80
        targetPort: 5000
        protocol: TCP
        name: http
