apiVersion: v1
kind: Service
metadata:
  name: {{ include "onix-postgres.fullname" . }}
  labels:
    {{- include "onix-postgres.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  selector:
    {{- include "onix-postgres.selectorLabels" . | nindent 4 }}
  ports:
    - name: postgres
      port: {{ .Values.service.port }}
      targetPort: postgres
